export const AUDIO_ACTIVE = 'AUDIO_ACTIVE'
export const AUDIO_DESACTIVE = 'AUDIO_DESACTIVE'
export const PAGE_NEXT = 'PAGE_NEXT'
export const PAGE_PREV = 'PAGE_PREV'
export const PAGE_DOUBLENEXT = 'PAGE_DOUBLENEXT'
export const PAGE_DOUBLEPREV = 'PAGE_DOUBLEPREV'
export const GROUP_SELECT = 'GROUP_SELECT'
export const PAGE_CHANGE = 'PAGE_CHANGE'
export const HARD_WORD_SELECTED = 'HARD_WORD_SELECTED'

export const MAX_PAGE_TEXTBOOK = 29
export const MIN_PAGE_TEXTBOOK = 0